### ISSUE TITLE
Maxing out at 5 objects per juggler

### ISSUE THREAD

**Issue by markadamdouglass** [prechac/prech.ac#3]
It seems this tool is maxing out at 5 objects per juggler.

For example, when I put in: 

http://prech.ac/2:6.5p

The pattern does not come up.

The link that is developed is: 

http://prechacthis.org/index.php?persons=2&objects=2or3or4or5or6or7or8or9or10&lengths=1&max=8&passesmin=1&passesmax=_&jugglerdoes=6.5p&exclude=&clubdoes=&react=&results=42

The key part being: 

objects=2or3or4or5or6or7or8or9or10

I had a little look in your code, but I do not fully understand Ruby. 

In the file: 

/lib/app.rb

I found: 

```
def objects_string
    (number_of_people..(number_of_people * 5)).to_a.join('or')
  end
```

It seems that increasing the number from 5 would resolve the issue, unless of course it would cause issues with the http://prechacthis.org/ website. 

Unsure what a reasonable amount is to increase 5 to. Possibly  somewhere in the range 7-10.

Side Note: I love this little tool. Very useful.

**Comment by amiel** [comment]
Hi @markadamdouglass, I'm so glad you find prech.ac useful.

You're totally right. I guess I hard-coded 5 per juggler since I figured searching for complex patterns might max out around there, but we can totally raise that number. I'm not sure what the performance implications from prechacthis.org might be to having too many options, and 10 objects per juggler seems a bit extreme. 7 seems fairly reasonable to me.

**Comment by markadamdouglass** [comment]
Hello @amiel 

Agreed. 7 seems very reasonable. 

If I ever need more than that, I’ll search for the pattern manually. 

Thank you.
